// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetCDNsHandlerFunc turns a function with the right signature into a get c d ns handler
type GetCDNsHandlerFunc func(GetCDNsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCDNsHandlerFunc) Handle(params GetCDNsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetCDNsHandler interface for that can handle valid get c d ns params
type GetCDNsHandler interface {
	Handle(GetCDNsParams, interface{}) middleware.Responder
}

// NewGetCDNs creates a new http.Handler for the get c d ns operation
func NewGetCDNs(ctx *middleware.Context, handler GetCDNsHandler) *GetCDNs {
	return &GetCDNs{Context: ctx, Handler: handler}
}

/*GetCDNs swagger:route GET /cdns CDN getCDNs

Retrieve a list of CDNs

*/
type GetCDNs struct {
	Context *middleware.Context
	Handler GetCDNsHandler
}

func (o *GetCDNs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCDNsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
