// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCDNsParams creates a new GetCDNsParams object
// with the default values initialized.
func NewGetCDNsParams() GetCDNsParams {
	var ()
	return GetCDNsParams{}
}

// GetCDNsParams contains all the bound params for the get c d ns operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetCDNs
type GetCDNsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Enables Domain Name System Security Extensions (DNSSEC) for the CDN
	  In: query
	*/
	DnssecEnabled *string
	/*The domain name for the CDN
	  In: query
	*/
	DomainName *string
	/*Unique identifier for the CDN
	  In: query
	*/
	ID *string
	/*The CDN name for the CDN
	  In: query
	*/
	Name *string
	/*
	  In: query
	*/
	Orderby *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetCDNsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qDnssecEnabled, qhkDnssecEnabled, _ := qs.GetOK("dnssecEnabled")
	if err := o.bindDnssecEnabled(qDnssecEnabled, qhkDnssecEnabled, route.Formats); err != nil {
		res = append(res, err)
	}

	qDomainName, qhkDomainName, _ := qs.GetOK("domainName")
	if err := o.bindDomainName(qDomainName, qhkDomainName, route.Formats); err != nil {
		res = append(res, err)
	}

	qID, qhkID, _ := qs.GetOK("id")
	if err := o.bindID(qID, qhkID, route.Formats); err != nil {
		res = append(res, err)
	}

	qName, qhkName, _ := qs.GetOK("name")
	if err := o.bindName(qName, qhkName, route.Formats); err != nil {
		res = append(res, err)
	}

	qOrderby, qhkOrderby, _ := qs.GetOK("orderby")
	if err := o.bindOrderby(qOrderby, qhkOrderby, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCDNsParams) bindDnssecEnabled(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.DnssecEnabled = &raw

	return nil
}

func (o *GetCDNsParams) bindDomainName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.DomainName = &raw

	return nil
}

func (o *GetCDNsParams) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.ID = &raw

	return nil
}

func (o *GetCDNsParams) bindName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Name = &raw

	return nil
}

func (o *GetCDNsParams) bindOrderby(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Orderby = &raw

	return nil
}
