// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/apache/incubator-trafficcontrol.tor-api/traffic_ops/traffic_ops_golang/toserver/models"
)

// PostCDNOKCode is the HTTP code returned for type PostCDNOK
const PostCDNOKCode int = 200

/*PostCDNOK Alerts - informs the client of server side messages

swagger:response postCDNOK
*/
type PostCDNOK struct {

	/*
	  In: Body
	*/
	Payload models.PostCDNOKBody `json:"body,omitempty"`
}

// NewPostCDNOK creates PostCDNOK with default headers values
func NewPostCDNOK() *PostCDNOK {
	return &PostCDNOK{}
}

// WithPayload adds the payload to the post c d n o k response
func (o *PostCDNOK) WithPayload(payload models.PostCDNOKBody) *PostCDNOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post c d n o k response
func (o *PostCDNOK) SetPayload(payload models.PostCDNOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostCDNOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.PostCDNOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
