// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/apache/incubator-trafficcontrol.tor-api/traffic_ops/traffic_ops_golang/toclient/models"
)

// DeleteStatusOKCode is the HTTP code returned for type DeleteStatusOK
const DeleteStatusOKCode int = 200

/*DeleteStatusOK Alerts - informs the client of server side messages

swagger:response deleteStatusOK
*/
type DeleteStatusOK struct {

	/*
	  In: Body
	*/
	Payload models.DeleteStatusOKBody `json:"body,omitempty"`
}

// NewDeleteStatusOK creates DeleteStatusOK with default headers values
func NewDeleteStatusOK() *DeleteStatusOK {
	return &DeleteStatusOK{}
}

// WithPayload adds the payload to the delete status o k response
func (o *DeleteStatusOK) WithPayload(payload models.DeleteStatusOKBody) *DeleteStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete status o k response
func (o *DeleteStatusOK) SetPayload(payload models.DeleteStatusOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.DeleteStatusOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
