// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
)

// GetStatusesURL generates an URL for the get statuses operation
type GetStatusesURL struct {
	Description *string
	ID          *string
	Name        *string
	Orderby     *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetStatusesURL) WithBasePath(bp string) *GetStatusesURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetStatusesURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetStatusesURL) Build() (*url.URL, error) {
	var result url.URL

	var _path = "/statuses"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api/1.3"
	}
	result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var description string
	if o.Description != nil {
		description = *o.Description
	}
	if description != "" {
		qs.Set("description", description)
	}

	var id string
	if o.ID != nil {
		id = *o.ID
	}
	if id != "" {
		qs.Set("id", id)
	}

	var name string
	if o.Name != nil {
		name = *o.Name
	}
	if name != "" {
		qs.Set("name", name)
	}

	var orderby string
	if o.Orderby != nil {
		orderby = *o.Orderby
	}
	if orderby != "" {
		qs.Set("orderby", orderby)
	}

	result.RawQuery = qs.Encode()

	return &result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetStatusesURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetStatusesURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetStatusesURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetStatusesURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetStatusesURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetStatusesURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
