// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostStatusHandlerFunc turns a function with the right signature into a post status handler
type PostStatusHandlerFunc func(PostStatusParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostStatusHandlerFunc) Handle(params PostStatusParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostStatusHandler interface for that can handle valid post status params
type PostStatusHandler interface {
	Handle(PostStatusParams, interface{}) middleware.Responder
}

// NewPostStatus creates a new http.Handler for the post status operation
func NewPostStatus(ctx *middleware.Context, handler PostStatusHandler) *PostStatus {
	return &PostStatus{Context: ctx, Handler: handler}
}

/*PostStatus swagger:route POST /statuses Status postStatus

Create a Status

*/
type PostStatus struct {
	Context *middleware.Context
	Handler PostStatusHandler
}

func (o *PostStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostStatusParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
