// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/apache/incubator-trafficcontrol.tor-api/traffic_ops/traffic_ops_golang/toclient/models"
)

// PutStatusOKCode is the HTTP code returned for type PutStatusOK
const PutStatusOKCode int = 200

/*PutStatusOK Status -  StatusResponse to get the "response" top level key

swagger:response putStatusOK
*/
type PutStatusOK struct {

	/*
	  In: Body
	*/
	Payload *models.StatusResponse `json:"body,omitempty"`
}

// NewPutStatusOK creates PutStatusOK with default headers values
func NewPutStatusOK() *PutStatusOK {
	return &PutStatusOK{}
}

// WithPayload adds the payload to the put status o k response
func (o *PutStatusOK) WithPayload(payload *models.StatusResponse) *PutStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put status o k response
func (o *PutStatusOK) SetPayload(payload *models.StatusResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
