// Code generated by go-swagger; DO NOT EDIT.

package asn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetASNByIDHandlerFunc turns a function with the right signature into a get a s n by Id handler
type GetASNByIDHandlerFunc func(GetASNByIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetASNByIDHandlerFunc) Handle(params GetASNByIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetASNByIDHandler interface for that can handle valid get a s n by Id params
type GetASNByIDHandler interface {
	Handle(GetASNByIDParams, interface{}) middleware.Responder
}

// NewGetASNByID creates a new http.Handler for the get a s n by Id operation
func NewGetASNByID(ctx *middleware.Context, handler GetASNByIDHandler) *GetASNByID {
	return &GetASNByID{Context: ctx, Handler: handler}
}

/*GetASNByID swagger:route GET /asns/{id} ASN getASNById

Retrieve a specific ASN

*/
type GetASNByID struct {
	Context *middleware.Context
	Handler GetASNByIDHandler
}

func (o *GetASNByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetASNByIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
