// Code generated by go-swagger; DO NOT EDIT.

package asn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/apache/incubator-trafficcontrol.tor-api/traffic_ops/traffic_ops_golang/toserver/models"
)

// PostASNOKCode is the HTTP code returned for type PostASNOK
const PostASNOKCode int = 200

/*PostASNOK Alerts - informs the client of server side messages

swagger:response postASNOK
*/
type PostASNOK struct {

	/*
	  In: Body
	*/
	Payload models.PostASNOKBody `json:"body,omitempty"`
}

// NewPostASNOK creates PostASNOK with default headers values
func NewPostASNOK() *PostASNOK {
	return &PostASNOK{}
}

// WithPayload adds the payload to the post a s n o k response
func (o *PostASNOK) WithPayload(payload models.PostASNOKBody) *PostASNOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post a s n o k response
func (o *PostASNOK) SetPayload(payload models.PostASNOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostASNOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.PostASNOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
