// Code generated by go-swagger; DO NOT EDIT.

package asn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/apache/incubator-trafficcontrol.tor-api/traffic_ops/traffic_ops_golang/toserver/models"
)

// PutASNOKCode is the HTTP code returned for type PutASNOK
const PutASNOKCode int = 200

/*PutASNOK ASN -  ASNResponse to get the "response" top level key

swagger:response putASNOK
*/
type PutASNOK struct {

	/*
	  In: Body
	*/
	Payload *models.ASNResponse `json:"body,omitempty"`
}

// NewPutASNOK creates PutASNOK with default headers values
func NewPutASNOK() *PutASNOK {
	return &PutASNOK{}
}

// WithPayload adds the payload to the put a s n o k response
func (o *PutASNOK) WithPayload(payload *models.ASNResponse) *PutASNOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put a s n o k response
func (o *PutASNOK) SetPayload(payload *models.ASNResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutASNOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
