// Code generated by go-swagger; DO NOT EDIT.

package asn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PutASNHandlerFunc turns a function with the right signature into a put a s n handler
type PutASNHandlerFunc func(PutASNParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PutASNHandlerFunc) Handle(params PutASNParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PutASNHandler interface for that can handle valid put a s n params
type PutASNHandler interface {
	Handle(PutASNParams, interface{}) middleware.Responder
}

// NewPutASN creates a new http.Handler for the put a s n operation
func NewPutASN(ctx *middleware.Context, handler PutASNHandler) *PutASN {
	return &PutASN{Context: ctx, Handler: handler}
}

/*PutASN swagger:route PUT /asns/{id} ASN putASN

Update a ASN

*/
type PutASN struct {
	Context *middleware.Context
	Handler PutASNHandler
}

func (o *PutASN) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutASNParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
