// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/apache/incubator-trafficcontrol/traffic_ops/traffic_ops_golang/toclient/client/asn"
	"github.com/apache/incubator-trafficcontrol/traffic_ops/traffic_ops_golang/toclient/client/cdn"
	"github.com/apache/incubator-trafficcontrol/traffic_ops/traffic_ops_golang/toclient/client/division"
	"github.com/apache/incubator-trafficcontrol/traffic_ops/traffic_ops_golang/toclient/client/region"
	"github.com/apache/incubator-trafficcontrol/traffic_ops/traffic_ops_golang/toclient/client/status"
)

// Default traffic ops HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost:8443"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/api/1.3"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http", "https"}

// NewHTTPClient creates a new traffic ops HTTP client.
func NewHTTPClient(formats strfmt.Registry) *TrafficOps {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new traffic ops HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *TrafficOps {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new traffic ops client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *TrafficOps {
	cli := new(TrafficOps)
	cli.Transport = transport

	cli.Asn = asn.New(transport, formats)

	cli.Cdn = cdn.New(transport, formats)

	cli.Division = division.New(transport, formats)

	cli.Region = region.New(transport, formats)

	cli.Status = status.New(transport, formats)

	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// TrafficOps is a client for traffic ops
type TrafficOps struct {
	Asn *asn.Client

	Cdn *cdn.Client

	Division *division.Client

	Region *region.Client

	Status *status.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *TrafficOps) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.Asn.SetTransport(transport)

	c.Cdn.SetTransport(transport)

	c.Division.SetTransport(transport)

	c.Region.SetTransport(transport)

	c.Status.SetTransport(transport)

}
