// Code generated by go-swagger; DO NOT EDIT.

package region

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/apache/incubator-trafficcontrol.tor-api/traffic_ops/traffic_ops_golang/toclient/models"
)

// PostRegionOKCode is the HTTP code returned for type PostRegionOK
const PostRegionOKCode int = 200

/*PostRegionOK Alerts - informs the client of server side messages

swagger:response postRegionOK
*/
type PostRegionOK struct {

	/*
	  In: Body
	*/
	Payload models.PostRegionOKBody `json:"body,omitempty"`
}

// NewPostRegionOK creates PostRegionOK with default headers values
func NewPostRegionOK() *PostRegionOK {
	return &PostRegionOK{}
}

// WithPayload adds the payload to the post region o k response
func (o *PostRegionOK) WithPayload(payload models.PostRegionOKBody) *PostRegionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post region o k response
func (o *PostRegionOK) SetPayload(payload models.PostRegionOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostRegionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.PostRegionOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
