// Code generated by go-swagger; DO NOT EDIT.

package region

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/apache/incubator-trafficcontrol.tor-api/traffic_ops/traffic_ops_golang/toclient/models"
)

// PutRegionOKCode is the HTTP code returned for type PutRegionOK
const PutRegionOKCode int = 200

/*PutRegionOK Region -  RegionResponse to get the "response" top level key

swagger:response putRegionOK
*/
type PutRegionOK struct {

	/*
	  In: Body
	*/
	Payload *models.RegionResponse `json:"body,omitempty"`
}

// NewPutRegionOK creates PutRegionOK with default headers values
func NewPutRegionOK() *PutRegionOK {
	return &PutRegionOK{}
}

// WithPayload adds the payload to the put region o k response
func (o *PutRegionOK) WithPayload(payload *models.RegionResponse) *PutRegionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put region o k response
func (o *PutRegionOK) SetPayload(payload *models.RegionResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutRegionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
