// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi TrafficOps API
The following REST APIs are used by the Traffic Portal UI along with several Traffic Control backend component and services.

This documentation is fully compliant with the Swagger 2.0 specification


    Schemes:
      http
      https
    Host: localhost:8443
    BasePath: /api/1.3
    Version: 1.3
    License: Apache 2 https://github.com/apache/incubator-trafficcontrol/blob/master/LICENSE
    Contact: Traffic Control Dev List<dev@trafficcontrol.incubator.apache.org> http://traffic-control-cdn.readthedocs.io/en/latest/index.html

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
