// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteStatusHandlerFunc turns a function with the right signature into a delete status handler
type DeleteStatusHandlerFunc func(DeleteStatusParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteStatusHandlerFunc) Handle(params DeleteStatusParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteStatusHandler interface for that can handle valid delete status params
type DeleteStatusHandler interface {
	Handle(DeleteStatusParams, interface{}) middleware.Responder
}

// NewDeleteStatus creates a new http.Handler for the delete status operation
func NewDeleteStatus(ctx *middleware.Context, handler DeleteStatusHandler) *DeleteStatus {
	return &DeleteStatus{Context: ctx, Handler: handler}
}

/*DeleteStatus swagger:route DELETE /statuses/{id} Status deleteStatus

Delete a Status

*/
type DeleteStatus struct {
	Context *middleware.Context
	Handler DeleteStatusHandler
}

func (o *DeleteStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteStatusParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
