// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetStatusesHandlerFunc turns a function with the right signature into a get statuses handler
type GetStatusesHandlerFunc func(GetStatusesParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetStatusesHandlerFunc) Handle(params GetStatusesParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetStatusesHandler interface for that can handle valid get statuses params
type GetStatusesHandler interface {
	Handle(GetStatusesParams, interface{}) middleware.Responder
}

// NewGetStatuses creates a new http.Handler for the get statuses operation
func NewGetStatuses(ctx *middleware.Context, handler GetStatusesHandler) *GetStatuses {
	return &GetStatuses{Context: ctx, Handler: handler}
}

/*GetStatuses swagger:route GET /statuses Status getStatuses

Retrieve a list of Statuses

*/
type GetStatuses struct {
	Context *middleware.Context
	Handler GetStatusesHandler
}

func (o *GetStatuses) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetStatusesParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
