// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/apache/incubator-trafficcontrol.tor-api/traffic_ops/traffic_ops_golang/toserver/models"
)

// PostStatusOKCode is the HTTP code returned for type PostStatusOK
const PostStatusOKCode int = 200

/*PostStatusOK Alerts - informs the client of server side messages

swagger:response postStatusOK
*/
type PostStatusOK struct {

	/*
	  In: Body
	*/
	Payload models.PostStatusOKBody `json:"body,omitempty"`
}

// NewPostStatusOK creates PostStatusOK with default headers values
func NewPostStatusOK() *PostStatusOK {
	return &PostStatusOK{}
}

// WithPayload adds the payload to the post status o k response
func (o *PostStatusOK) WithPayload(payload models.PostStatusOKBody) *PostStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post status o k response
func (o *PostStatusOK) SetPayload(payload models.PostStatusOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.PostStatusOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
