// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PutStatusHandlerFunc turns a function with the right signature into a put status handler
type PutStatusHandlerFunc func(PutStatusParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PutStatusHandlerFunc) Handle(params PutStatusParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PutStatusHandler interface for that can handle valid put status params
type PutStatusHandler interface {
	Handle(PutStatusParams, interface{}) middleware.Responder
}

// NewPutStatus creates a new http.Handler for the put status operation
func NewPutStatus(ctx *middleware.Context, handler PutStatusHandler) *PutStatus {
	return &PutStatus{Context: ctx, Handler: handler}
}

/*PutStatus swagger:route PUT /statuses/{id} Status putStatus

Update a Status

*/
type PutStatus struct {
	Context *middleware.Context
	Handler PutStatusHandler
}

func (o *PutStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutStatusParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
