# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

############################################################
# Dockerfile to build Traffic Ops container images
# Based on CentOS 7.2
############################################################

FROM centos:7
RUN yum -y install nmap-ncat openssl git

RUN mkdir -p /go/src/github.com/apache
WORKDIR /go/src/github.com/apache
RUN git clone https://github.com/apache/trafficcontrol

WORKDIR /opt
RUN ln -s /go/src/github.com/apache/trafficcontrol/traffic_ops/ /opt/traffic_ops

RUN git config --global user.email "tc@apache.org"
RUN git config --global user.name "Traffic Control"

#COPY --from=trafficops-perl /opt/traffic_ops/app/local /opt/traffic_ops/app/local
COPY --from=trafficops-perl /usr/local/go /usr/local/go

WORKDIR /opt/traffic_ops/app

ADD config.sh /
ADD run-go-clone.sh /
CMD /run-go-clone.sh
