// Code generated by go-swagger; DO NOT EDIT.

package region

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteRegionParams creates a new DeleteRegionParams object
// with the default values initialized.
func NewDeleteRegionParams() *DeleteRegionParams {
	var ()
	return &DeleteRegionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteRegionParamsWithTimeout creates a new DeleteRegionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteRegionParamsWithTimeout(timeout time.Duration) *DeleteRegionParams {
	var ()
	return &DeleteRegionParams{

		timeout: timeout,
	}
}

// NewDeleteRegionParamsWithContext creates a new DeleteRegionParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteRegionParamsWithContext(ctx context.Context) *DeleteRegionParams {
	var ()
	return &DeleteRegionParams{

		Context: ctx,
	}
}

// NewDeleteRegionParamsWithHTTPClient creates a new DeleteRegionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteRegionParamsWithHTTPClient(client *http.Client) *DeleteRegionParams {
	var ()
	return &DeleteRegionParams{
		HTTPClient: client,
	}
}

/*DeleteRegionParams contains all the parameters to send to the API endpoint
for the delete region operation typically these are written to a http.Request
*/
type DeleteRegionParams struct {

	/*ID
	  Id associated to the Region

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete region params
func (o *DeleteRegionParams) WithTimeout(timeout time.Duration) *DeleteRegionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete region params
func (o *DeleteRegionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete region params
func (o *DeleteRegionParams) WithContext(ctx context.Context) *DeleteRegionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete region params
func (o *DeleteRegionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete region params
func (o *DeleteRegionParams) WithHTTPClient(client *http.Client) *DeleteRegionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete region params
func (o *DeleteRegionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete region params
func (o *DeleteRegionParams) WithID(id int64) *DeleteRegionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete region params
func (o *DeleteRegionParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteRegionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
