// Code generated by go-swagger; DO NOT EDIT.

package region

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRegionByIDParams creates a new GetRegionByIDParams object
// with the default values initialized.
func NewGetRegionByIDParams() *GetRegionByIDParams {
	var ()
	return &GetRegionByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRegionByIDParamsWithTimeout creates a new GetRegionByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRegionByIDParamsWithTimeout(timeout time.Duration) *GetRegionByIDParams {
	var ()
	return &GetRegionByIDParams{

		timeout: timeout,
	}
}

// NewGetRegionByIDParamsWithContext creates a new GetRegionByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRegionByIDParamsWithContext(ctx context.Context) *GetRegionByIDParams {
	var ()
	return &GetRegionByIDParams{

		Context: ctx,
	}
}

// NewGetRegionByIDParamsWithHTTPClient creates a new GetRegionByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRegionByIDParamsWithHTTPClient(client *http.Client) *GetRegionByIDParams {
	var ()
	return &GetRegionByIDParams{
		HTTPClient: client,
	}
}

/*GetRegionByIDParams contains all the parameters to send to the API endpoint
for the get region by Id operation typically these are written to a http.Request
*/
type GetRegionByIDParams struct {

	/*ID
	  Id associated to the Region

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get region by Id params
func (o *GetRegionByIDParams) WithTimeout(timeout time.Duration) *GetRegionByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get region by Id params
func (o *GetRegionByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get region by Id params
func (o *GetRegionByIDParams) WithContext(ctx context.Context) *GetRegionByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get region by Id params
func (o *GetRegionByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get region by Id params
func (o *GetRegionByIDParams) WithHTTPClient(client *http.Client) *GetRegionByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get region by Id params
func (o *GetRegionByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get region by Id params
func (o *GetRegionByIDParams) WithID(id int64) *GetRegionByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get region by Id params
func (o *GetRegionByIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetRegionByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
