// Code generated by go-swagger; DO NOT EDIT.

package region

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/apache/incubator-trafficcontrol/traffic_ops/traffic_ops_golang/toclient/models"
)

// GetRegionByIDReader is a Reader for the GetRegionByID structure.
type GetRegionByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRegionByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetRegionByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetRegionByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetRegionByIDOK creates a GetRegionByIDOK with default headers values
func NewGetRegionByIDOK() *GetRegionByIDOK {
	return &GetRegionByIDOK{}
}

/*GetRegionByIDOK handles this case with default header values.

Regions -  RegionsResponse to get the "response" top level key
*/
type GetRegionByIDOK struct {
	Payload *models.RegionsResponse
}

func (o *GetRegionByIDOK) Error() string {
	return fmt.Sprintf("[GET /regions/{id}][%d] getRegionByIdOK  %+v", 200, o.Payload)
}

func (o *GetRegionByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RegionsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRegionByIDBadRequest creates a GetRegionByIDBadRequest with default headers values
func NewGetRegionByIDBadRequest() *GetRegionByIDBadRequest {
	return &GetRegionByIDBadRequest{}
}

/*GetRegionByIDBadRequest handles this case with default header values.

Alerts - informs the client of server side messages
*/
type GetRegionByIDBadRequest struct {
	Payload models.GetRegionByIDBadRequestBody
}

func (o *GetRegionByIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /regions/{id}][%d] getRegionByIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetRegionByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
