// Code generated by go-swagger; DO NOT EDIT.

package region

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/apache/incubator-trafficcontrol/traffic_ops/traffic_ops_golang/toclient/models"
)

// NewPostRegionParams creates a new PostRegionParams object
// with the default values initialized.
func NewPostRegionParams() *PostRegionParams {
	var ()
	return &PostRegionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostRegionParamsWithTimeout creates a new PostRegionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostRegionParamsWithTimeout(timeout time.Duration) *PostRegionParams {
	var ()
	return &PostRegionParams{

		timeout: timeout,
	}
}

// NewPostRegionParamsWithContext creates a new PostRegionParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostRegionParamsWithContext(ctx context.Context) *PostRegionParams {
	var ()
	return &PostRegionParams{

		Context: ctx,
	}
}

// NewPostRegionParamsWithHTTPClient creates a new PostRegionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostRegionParamsWithHTTPClient(client *http.Client) *PostRegionParams {
	var ()
	return &PostRegionParams{
		HTTPClient: client,
	}
}

/*PostRegionParams contains all the parameters to send to the API endpoint
for the post region operation typically these are written to a http.Request
*/
type PostRegionParams struct {

	/*Region
	  Region Request Body

	*/
	Region *models.Region

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post region params
func (o *PostRegionParams) WithTimeout(timeout time.Duration) *PostRegionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post region params
func (o *PostRegionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post region params
func (o *PostRegionParams) WithContext(ctx context.Context) *PostRegionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post region params
func (o *PostRegionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post region params
func (o *PostRegionParams) WithHTTPClient(client *http.Client) *PostRegionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post region params
func (o *PostRegionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRegion adds the region to the post region params
func (o *PostRegionParams) WithRegion(region *models.Region) *PostRegionParams {
	o.SetRegion(region)
	return o
}

// SetRegion adds the region to the post region params
func (o *PostRegionParams) SetRegion(region *models.Region) {
	o.Region = region
}

// WriteToRequest writes these params to a swagger request
func (o *PostRegionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Region != nil {
		if err := r.SetBodyParam(o.Region); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
