// Code generated by go-swagger; DO NOT EDIT.

package region

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new region API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for region API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
DeleteRegion Delete a Region
*/
func (a *Client) DeleteRegion(params *DeleteRegionParams, authInfo runtime.ClientAuthInfoWriter) (*DeleteRegionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteRegionParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "DeleteRegion",
		Method:             "DELETE",
		PathPattern:        "/regions/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeleteRegionReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*DeleteRegionOK), nil

}

/*
GetRegionByID Retrieve a specific Region
*/
func (a *Client) GetRegionByID(params *GetRegionByIDParams, authInfo runtime.ClientAuthInfoWriter) (*GetRegionByIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetRegionByIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetRegionById",
		Method:             "GET",
		PathPattern:        "/regions/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetRegionByIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetRegionByIDOK), nil

}

/*
GetRegions Retrieve a list of Regions
*/
func (a *Client) GetRegions(params *GetRegionsParams, authInfo runtime.ClientAuthInfoWriter) (*GetRegionsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetRegionsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetRegions",
		Method:             "GET",
		PathPattern:        "/regions",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetRegionsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetRegionsOK), nil

}

/*
PostRegion Create a Region
*/
func (a *Client) PostRegion(params *PostRegionParams, authInfo runtime.ClientAuthInfoWriter) (*PostRegionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostRegionParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PostRegion",
		Method:             "POST",
		PathPattern:        "/regions",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PostRegionReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PostRegionOK), nil

}

/*
PutRegion Update a Region
*/
func (a *Client) PutRegion(params *PutRegionParams, authInfo runtime.ClientAuthInfoWriter) (*PutRegionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPutRegionParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PutRegion",
		Method:             "PUT",
		PathPattern:        "/regions/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PutRegionReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PutRegionOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
