// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteCDNParams creates a new DeleteCDNParams object
// with the default values initialized.
func NewDeleteCDNParams() *DeleteCDNParams {
	var ()
	return &DeleteCDNParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCDNParamsWithTimeout creates a new DeleteCDNParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteCDNParamsWithTimeout(timeout time.Duration) *DeleteCDNParams {
	var ()
	return &DeleteCDNParams{

		timeout: timeout,
	}
}

// NewDeleteCDNParamsWithContext creates a new DeleteCDNParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteCDNParamsWithContext(ctx context.Context) *DeleteCDNParams {
	var ()
	return &DeleteCDNParams{

		Context: ctx,
	}
}

// NewDeleteCDNParamsWithHTTPClient creates a new DeleteCDNParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteCDNParamsWithHTTPClient(client *http.Client) *DeleteCDNParams {
	var ()
	return &DeleteCDNParams{
		HTTPClient: client,
	}
}

/*DeleteCDNParams contains all the parameters to send to the API endpoint
for the delete c d n operation typically these are written to a http.Request
*/
type DeleteCDNParams struct {

	/*ID
	  Id associated to the CDN

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete c d n params
func (o *DeleteCDNParams) WithTimeout(timeout time.Duration) *DeleteCDNParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete c d n params
func (o *DeleteCDNParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete c d n params
func (o *DeleteCDNParams) WithContext(ctx context.Context) *DeleteCDNParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete c d n params
func (o *DeleteCDNParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete c d n params
func (o *DeleteCDNParams) WithHTTPClient(client *http.Client) *DeleteCDNParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete c d n params
func (o *DeleteCDNParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete c d n params
func (o *DeleteCDNParams) WithID(id int64) *DeleteCDNParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete c d n params
func (o *DeleteCDNParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCDNParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
