// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/apache/incubator-trafficcontrol/traffic_ops/traffic_ops_golang/toclient/models"
)

// GetCDNsReader is a Reader for the GetCDNs structure.
type GetCDNsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCDNsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCDNsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetCDNsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCDNsOK creates a GetCDNsOK with default headers values
func NewGetCDNsOK() *GetCDNsOK {
	return &GetCDNsOK{}
}

/*GetCDNsOK handles this case with default header values.

CDNs -  CDNsResponse to get the "response" top level key
*/
type GetCDNsOK struct {
	Payload *models.CDNsResponse
}

func (o *GetCDNsOK) Error() string {
	return fmt.Sprintf("[GET /cdns][%d] getCDNsOK  %+v", 200, o.Payload)
}

func (o *GetCDNsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CDNsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCDNsBadRequest creates a GetCDNsBadRequest with default headers values
func NewGetCDNsBadRequest() *GetCDNsBadRequest {
	return &GetCDNsBadRequest{}
}

/*GetCDNsBadRequest handles this case with default header values.

Alerts - informs the client of server side messages
*/
type GetCDNsBadRequest struct {
	Payload models.GetCDNsBadRequestBody
}

func (o *GetCDNsBadRequest) Error() string {
	return fmt.Sprintf("[GET /cdns][%d] getCDNsBadRequest  %+v", 400, o.Payload)
}

func (o *GetCDNsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
