// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCDNByIDParams creates a new GetCDNByIDParams object
// with the default values initialized.
func NewGetCDNByIDParams() *GetCDNByIDParams {
	var ()
	return &GetCDNByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCDNByIDParamsWithTimeout creates a new GetCDNByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCDNByIDParamsWithTimeout(timeout time.Duration) *GetCDNByIDParams {
	var ()
	return &GetCDNByIDParams{

		timeout: timeout,
	}
}

// NewGetCDNByIDParamsWithContext creates a new GetCDNByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCDNByIDParamsWithContext(ctx context.Context) *GetCDNByIDParams {
	var ()
	return &GetCDNByIDParams{

		Context: ctx,
	}
}

// NewGetCDNByIDParamsWithHTTPClient creates a new GetCDNByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCDNByIDParamsWithHTTPClient(client *http.Client) *GetCDNByIDParams {
	var ()
	return &GetCDNByIDParams{
		HTTPClient: client,
	}
}

/*GetCDNByIDParams contains all the parameters to send to the API endpoint
for the get c d n by Id operation typically these are written to a http.Request
*/
type GetCDNByIDParams struct {

	/*ID
	  Id associated to the CDN

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get c d n by Id params
func (o *GetCDNByIDParams) WithTimeout(timeout time.Duration) *GetCDNByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get c d n by Id params
func (o *GetCDNByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get c d n by Id params
func (o *GetCDNByIDParams) WithContext(ctx context.Context) *GetCDNByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get c d n by Id params
func (o *GetCDNByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get c d n by Id params
func (o *GetCDNByIDParams) WithHTTPClient(client *http.Client) *GetCDNByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get c d n by Id params
func (o *GetCDNByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get c d n by Id params
func (o *GetCDNByIDParams) WithID(id int64) *GetCDNByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get c d n by Id params
func (o *GetCDNByIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetCDNByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
