// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/apache/incubator-trafficcontrol/traffic_ops/traffic_ops_golang/toclient/models"
)

// NewPostCDNParams creates a new PostCDNParams object
// with the default values initialized.
func NewPostCDNParams() *PostCDNParams {
	var ()
	return &PostCDNParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostCDNParamsWithTimeout creates a new PostCDNParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostCDNParamsWithTimeout(timeout time.Duration) *PostCDNParams {
	var ()
	return &PostCDNParams{

		timeout: timeout,
	}
}

// NewPostCDNParamsWithContext creates a new PostCDNParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostCDNParamsWithContext(ctx context.Context) *PostCDNParams {
	var ()
	return &PostCDNParams{

		Context: ctx,
	}
}

// NewPostCDNParamsWithHTTPClient creates a new PostCDNParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostCDNParamsWithHTTPClient(client *http.Client) *PostCDNParams {
	var ()
	return &PostCDNParams{
		HTTPClient: client,
	}
}

/*PostCDNParams contains all the parameters to send to the API endpoint
for the post c d n operation typically these are written to a http.Request
*/
type PostCDNParams struct {

	/*CDN
	  CDN Request Body

	*/
	CDN *models.CDN

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post c d n params
func (o *PostCDNParams) WithTimeout(timeout time.Duration) *PostCDNParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post c d n params
func (o *PostCDNParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post c d n params
func (o *PostCDNParams) WithContext(ctx context.Context) *PostCDNParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post c d n params
func (o *PostCDNParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post c d n params
func (o *PostCDNParams) WithHTTPClient(client *http.Client) *PostCDNParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post c d n params
func (o *PostCDNParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCDN adds the cDN to the post c d n params
func (o *PostCDNParams) WithCDN(cDN *models.CDN) *PostCDNParams {
	o.SetCDN(cDN)
	return o
}

// SetCDN adds the cDN to the post c d n params
func (o *PostCDNParams) SetCDN(cDN *models.CDN) {
	o.CDN = cDN
}

// WriteToRequest writes these params to a swagger request
func (o *PostCDNParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CDN != nil {
		if err := r.SetBodyParam(o.CDN); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
