// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/apache/incubator-trafficcontrol/traffic_ops/traffic_ops_golang/toclient/models"
)

// PutCDNReader is a Reader for the PutCDN structure.
type PutCDNReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutCDNReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutCDNOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutCDNOK creates a PutCDNOK with default headers values
func NewPutCDNOK() *PutCDNOK {
	return &PutCDNOK{}
}

/*PutCDNOK handles this case with default header values.

CDN -  CDNResponse to get the "response" top level key
*/
type PutCDNOK struct {
	Payload *models.CDNResponse
}

func (o *PutCDNOK) Error() string {
	return fmt.Sprintf("[PUT /cdns/{id}][%d] putCDNOK  %+v", 200, o.Payload)
}

func (o *PutCDNOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CDNResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
