// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/apache/incubator-trafficcontrol/traffic_ops/traffic_ops_golang/toclient/models"
)

// NewPutCDNParams creates a new PutCDNParams object
// with the default values initialized.
func NewPutCDNParams() *PutCDNParams {
	var ()
	return &PutCDNParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutCDNParamsWithTimeout creates a new PutCDNParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutCDNParamsWithTimeout(timeout time.Duration) *PutCDNParams {
	var ()
	return &PutCDNParams{

		timeout: timeout,
	}
}

// NewPutCDNParamsWithContext creates a new PutCDNParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutCDNParamsWithContext(ctx context.Context) *PutCDNParams {
	var ()
	return &PutCDNParams{

		Context: ctx,
	}
}

// NewPutCDNParamsWithHTTPClient creates a new PutCDNParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutCDNParamsWithHTTPClient(client *http.Client) *PutCDNParams {
	var ()
	return &PutCDNParams{
		HTTPClient: client,
	}
}

/*PutCDNParams contains all the parameters to send to the API endpoint
for the put c d n operation typically these are written to a http.Request
*/
type PutCDNParams struct {

	/*CDN
	  CDN Request Body

	*/
	CDN *models.CDN
	/*ID
	  ID

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put c d n params
func (o *PutCDNParams) WithTimeout(timeout time.Duration) *PutCDNParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put c d n params
func (o *PutCDNParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put c d n params
func (o *PutCDNParams) WithContext(ctx context.Context) *PutCDNParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put c d n params
func (o *PutCDNParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put c d n params
func (o *PutCDNParams) WithHTTPClient(client *http.Client) *PutCDNParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put c d n params
func (o *PutCDNParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCDN adds the cDN to the put c d n params
func (o *PutCDNParams) WithCDN(cDN *models.CDN) *PutCDNParams {
	o.SetCDN(cDN)
	return o
}

// SetCDN adds the cDN to the put c d n params
func (o *PutCDNParams) SetCDN(cDN *models.CDN) {
	o.CDN = cDN
}

// WithID adds the id to the put c d n params
func (o *PutCDNParams) WithID(id int64) *PutCDNParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put c d n params
func (o *PutCDNParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutCDNParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CDN != nil {
		if err := r.SetBodyParam(o.CDN); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
