// Code generated by go-swagger; DO NOT EDIT.

package division

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteDivisionHandlerFunc turns a function with the right signature into a delete division handler
type DeleteDivisionHandlerFunc func(DeleteDivisionParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteDivisionHandlerFunc) Handle(params DeleteDivisionParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteDivisionHandler interface for that can handle valid delete division params
type DeleteDivisionHandler interface {
	Handle(DeleteDivisionParams, interface{}) middleware.Responder
}

// NewDeleteDivision creates a new http.Handler for the delete division operation
func NewDeleteDivision(ctx *middleware.Context, handler DeleteDivisionHandler) *DeleteDivision {
	return &DeleteDivision{Context: ctx, Handler: handler}
}

/*DeleteDivision swagger:route DELETE /divisions/{id} Division deleteDivision

Delete a Division

*/
type DeleteDivision struct {
	Context *middleware.Context
	Handler DeleteDivisionHandler
}

func (o *DeleteDivision) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteDivisionParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
