// Code generated by go-swagger; DO NOT EDIT.

package division

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/apache/incubator-trafficcontrol.tor-api/traffic_ops/traffic_ops_golang/toserver/models"
)

// DeleteDivisionOKCode is the HTTP code returned for type DeleteDivisionOK
const DeleteDivisionOKCode int = 200

/*DeleteDivisionOK Alerts - informs the client of server side messages

swagger:response deleteDivisionOK
*/
type DeleteDivisionOK struct {

	/*
	  In: Body
	*/
	Payload models.DeleteDivisionOKBody `json:"body,omitempty"`
}

// NewDeleteDivisionOK creates DeleteDivisionOK with default headers values
func NewDeleteDivisionOK() *DeleteDivisionOK {
	return &DeleteDivisionOK{}
}

// WithPayload adds the payload to the delete division o k response
func (o *DeleteDivisionOK) WithPayload(payload models.DeleteDivisionOKBody) *DeleteDivisionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete division o k response
func (o *DeleteDivisionOK) SetPayload(payload models.DeleteDivisionOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteDivisionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.DeleteDivisionOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
