// Code generated by go-swagger; DO NOT EDIT.

package division

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetDivisionByIDHandlerFunc turns a function with the right signature into a get division by Id handler
type GetDivisionByIDHandlerFunc func(GetDivisionByIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDivisionByIDHandlerFunc) Handle(params GetDivisionByIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetDivisionByIDHandler interface for that can handle valid get division by Id params
type GetDivisionByIDHandler interface {
	Handle(GetDivisionByIDParams, interface{}) middleware.Responder
}

// NewGetDivisionByID creates a new http.Handler for the get division by Id operation
func NewGetDivisionByID(ctx *middleware.Context, handler GetDivisionByIDHandler) *GetDivisionByID {
	return &GetDivisionByID{Context: ctx, Handler: handler}
}

/*GetDivisionByID swagger:route GET /divisions/{id} Division getDivisionById

Retrieve a specific Division

*/
type GetDivisionByID struct {
	Context *middleware.Context
	Handler GetDivisionByIDHandler
}

func (o *GetDivisionByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetDivisionByIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
