// Code generated by go-swagger; DO NOT EDIT.

package division

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetDivisionsHandlerFunc turns a function with the right signature into a get divisions handler
type GetDivisionsHandlerFunc func(GetDivisionsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDivisionsHandlerFunc) Handle(params GetDivisionsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetDivisionsHandler interface for that can handle valid get divisions params
type GetDivisionsHandler interface {
	Handle(GetDivisionsParams, interface{}) middleware.Responder
}

// NewGetDivisions creates a new http.Handler for the get divisions operation
func NewGetDivisions(ctx *middleware.Context, handler GetDivisionsHandler) *GetDivisions {
	return &GetDivisions{Context: ctx, Handler: handler}
}

/*GetDivisions swagger:route GET /divisions Division getDivisions

Retrieve a list of Divisions

*/
type GetDivisions struct {
	Context *middleware.Context
	Handler GetDivisionsHandler
}

func (o *GetDivisions) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetDivisionsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
