// Code generated by go-swagger; DO NOT EDIT.

package division

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PutDivisionHandlerFunc turns a function with the right signature into a put division handler
type PutDivisionHandlerFunc func(PutDivisionParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PutDivisionHandlerFunc) Handle(params PutDivisionParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PutDivisionHandler interface for that can handle valid put division params
type PutDivisionHandler interface {
	Handle(PutDivisionParams, interface{}) middleware.Responder
}

// NewPutDivision creates a new http.Handler for the put division operation
func NewPutDivision(ctx *middleware.Context, handler PutDivisionHandler) *PutDivision {
	return &PutDivision{Context: ctx, Handler: handler}
}

/*PutDivision swagger:route PUT /divisions/{id} Division putDivision

Update a Division

*/
type PutDivision struct {
	Context *middleware.Context
	Handler PutDivisionHandler
}

func (o *PutDivision) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutDivisionParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
