// Code generated by go-swagger; DO NOT EDIT.

package division

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/apache/incubator-trafficcontrol.tor-api/traffic_ops/traffic_ops_golang/toclient/models"
)

// PostDivisionOKCode is the HTTP code returned for type PostDivisionOK
const PostDivisionOKCode int = 200

/*PostDivisionOK Alerts - informs the client of server side messages

swagger:response postDivisionOK
*/
type PostDivisionOK struct {

	/*
	  In: Body
	*/
	Payload models.PostDivisionOKBody `json:"body,omitempty"`
}

// NewPostDivisionOK creates PostDivisionOK with default headers values
func NewPostDivisionOK() *PostDivisionOK {
	return &PostDivisionOK{}
}

// WithPayload adds the payload to the post division o k response
func (o *PostDivisionOK) WithPayload(payload models.PostDivisionOKBody) *PostDivisionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post division o k response
func (o *PostDivisionOK) SetPayload(payload models.PostDivisionOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostDivisionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.PostDivisionOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
