// Code generated by go-swagger; DO NOT EDIT.

package division

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/apache/incubator-trafficcontrol.tor-api/traffic_ops/traffic_ops_golang/toclient/models"
)

// PutDivisionOKCode is the HTTP code returned for type PutDivisionOK
const PutDivisionOKCode int = 200

/*PutDivisionOK Division -  DivisionResponse to get the "response" top level key

swagger:response putDivisionOK
*/
type PutDivisionOK struct {

	/*
	  In: Body
	*/
	Payload *models.DivisionResponse `json:"body,omitempty"`
}

// NewPutDivisionOK creates PutDivisionOK with default headers values
func NewPutDivisionOK() *PutDivisionOK {
	return &PutDivisionOK{}
}

// WithPayload adds the payload to the put division o k response
func (o *PutDivisionOK) WithPayload(payload *models.DivisionResponse) *PutDivisionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put division o k response
func (o *PutDivisionOK) SetPayload(payload *models.DivisionResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutDivisionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
