// Code generated by go-swagger; DO NOT EDIT.

package asn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteASNParams creates a new DeleteASNParams object
// with the default values initialized.
func NewDeleteASNParams() *DeleteASNParams {
	var ()
	return &DeleteASNParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteASNParamsWithTimeout creates a new DeleteASNParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteASNParamsWithTimeout(timeout time.Duration) *DeleteASNParams {
	var ()
	return &DeleteASNParams{

		timeout: timeout,
	}
}

// NewDeleteASNParamsWithContext creates a new DeleteASNParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteASNParamsWithContext(ctx context.Context) *DeleteASNParams {
	var ()
	return &DeleteASNParams{

		Context: ctx,
	}
}

// NewDeleteASNParamsWithHTTPClient creates a new DeleteASNParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteASNParamsWithHTTPClient(client *http.Client) *DeleteASNParams {
	var ()
	return &DeleteASNParams{
		HTTPClient: client,
	}
}

/*DeleteASNParams contains all the parameters to send to the API endpoint
for the delete a s n operation typically these are written to a http.Request
*/
type DeleteASNParams struct {

	/*ID
	  Id associated to the ASN

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete a s n params
func (o *DeleteASNParams) WithTimeout(timeout time.Duration) *DeleteASNParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete a s n params
func (o *DeleteASNParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete a s n params
func (o *DeleteASNParams) WithContext(ctx context.Context) *DeleteASNParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete a s n params
func (o *DeleteASNParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete a s n params
func (o *DeleteASNParams) WithHTTPClient(client *http.Client) *DeleteASNParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete a s n params
func (o *DeleteASNParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete a s n params
func (o *DeleteASNParams) WithID(id int64) *DeleteASNParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete a s n params
func (o *DeleteASNParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteASNParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
