// Code generated by go-swagger; DO NOT EDIT.

package asn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetASNByIDParams creates a new GetASNByIDParams object
// with the default values initialized.
func NewGetASNByIDParams() *GetASNByIDParams {
	var ()
	return &GetASNByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetASNByIDParamsWithTimeout creates a new GetASNByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetASNByIDParamsWithTimeout(timeout time.Duration) *GetASNByIDParams {
	var ()
	return &GetASNByIDParams{

		timeout: timeout,
	}
}

// NewGetASNByIDParamsWithContext creates a new GetASNByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetASNByIDParamsWithContext(ctx context.Context) *GetASNByIDParams {
	var ()
	return &GetASNByIDParams{

		Context: ctx,
	}
}

// NewGetASNByIDParamsWithHTTPClient creates a new GetASNByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetASNByIDParamsWithHTTPClient(client *http.Client) *GetASNByIDParams {
	var ()
	return &GetASNByIDParams{
		HTTPClient: client,
	}
}

/*GetASNByIDParams contains all the parameters to send to the API endpoint
for the get a s n by Id operation typically these are written to a http.Request
*/
type GetASNByIDParams struct {

	/*ID
	  Id associated to the ASN

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get a s n by Id params
func (o *GetASNByIDParams) WithTimeout(timeout time.Duration) *GetASNByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get a s n by Id params
func (o *GetASNByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get a s n by Id params
func (o *GetASNByIDParams) WithContext(ctx context.Context) *GetASNByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get a s n by Id params
func (o *GetASNByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get a s n by Id params
func (o *GetASNByIDParams) WithHTTPClient(client *http.Client) *GetASNByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get a s n by Id params
func (o *GetASNByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get a s n by Id params
func (o *GetASNByIDParams) WithID(id int64) *GetASNByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get a s n by Id params
func (o *GetASNByIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetASNByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
