// Code generated by go-swagger; DO NOT EDIT.

package asn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/apache/incubator-trafficcontrol/traffic_ops/traffic_ops_golang/toclient/models"
)

// GetASNsReader is a Reader for the GetASNs structure.
type GetASNsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetASNsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetASNsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetASNsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetASNsOK creates a GetASNsOK with default headers values
func NewGetASNsOK() *GetASNsOK {
	return &GetASNsOK{}
}

/*GetASNsOK handles this case with default header values.

ASNs -  ASNsResponse to get the "response" top level key
*/
type GetASNsOK struct {
	Payload *models.ASNsResponse
}

func (o *GetASNsOK) Error() string {
	return fmt.Sprintf("[GET /asns][%d] getASNsOK  %+v", 200, o.Payload)
}

func (o *GetASNsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ASNsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetASNsBadRequest creates a GetASNsBadRequest with default headers values
func NewGetASNsBadRequest() *GetASNsBadRequest {
	return &GetASNsBadRequest{}
}

/*GetASNsBadRequest handles this case with default header values.

Alerts - informs the client of server side messages
*/
type GetASNsBadRequest struct {
	Payload models.GetASNsBadRequestBody
}

func (o *GetASNsBadRequest) Error() string {
	return fmt.Sprintf("[GET /asns][%d] getASNsBadRequest  %+v", 400, o.Payload)
}

func (o *GetASNsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
