// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteStatusParams creates a new DeleteStatusParams object
// with the default values initialized.
func NewDeleteStatusParams() *DeleteStatusParams {
	var ()
	return &DeleteStatusParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteStatusParamsWithTimeout creates a new DeleteStatusParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteStatusParamsWithTimeout(timeout time.Duration) *DeleteStatusParams {
	var ()
	return &DeleteStatusParams{

		timeout: timeout,
	}
}

// NewDeleteStatusParamsWithContext creates a new DeleteStatusParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteStatusParamsWithContext(ctx context.Context) *DeleteStatusParams {
	var ()
	return &DeleteStatusParams{

		Context: ctx,
	}
}

// NewDeleteStatusParamsWithHTTPClient creates a new DeleteStatusParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteStatusParamsWithHTTPClient(client *http.Client) *DeleteStatusParams {
	var ()
	return &DeleteStatusParams{
		HTTPClient: client,
	}
}

/*DeleteStatusParams contains all the parameters to send to the API endpoint
for the delete status operation typically these are written to a http.Request
*/
type DeleteStatusParams struct {

	/*ID
	  Id associated to the Status

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete status params
func (o *DeleteStatusParams) WithTimeout(timeout time.Duration) *DeleteStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete status params
func (o *DeleteStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete status params
func (o *DeleteStatusParams) WithContext(ctx context.Context) *DeleteStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete status params
func (o *DeleteStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete status params
func (o *DeleteStatusParams) WithHTTPClient(client *http.Client) *DeleteStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete status params
func (o *DeleteStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete status params
func (o *DeleteStatusParams) WithID(id int64) *DeleteStatusParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete status params
func (o *DeleteStatusParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
