// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetStatusByIDParams creates a new GetStatusByIDParams object
// with the default values initialized.
func NewGetStatusByIDParams() *GetStatusByIDParams {
	var ()
	return &GetStatusByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetStatusByIDParamsWithTimeout creates a new GetStatusByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetStatusByIDParamsWithTimeout(timeout time.Duration) *GetStatusByIDParams {
	var ()
	return &GetStatusByIDParams{

		timeout: timeout,
	}
}

// NewGetStatusByIDParamsWithContext creates a new GetStatusByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetStatusByIDParamsWithContext(ctx context.Context) *GetStatusByIDParams {
	var ()
	return &GetStatusByIDParams{

		Context: ctx,
	}
}

// NewGetStatusByIDParamsWithHTTPClient creates a new GetStatusByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetStatusByIDParamsWithHTTPClient(client *http.Client) *GetStatusByIDParams {
	var ()
	return &GetStatusByIDParams{
		HTTPClient: client,
	}
}

/*GetStatusByIDParams contains all the parameters to send to the API endpoint
for the get status by Id operation typically these are written to a http.Request
*/
type GetStatusByIDParams struct {

	/*ID
	  Id associated to the Status

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get status by Id params
func (o *GetStatusByIDParams) WithTimeout(timeout time.Duration) *GetStatusByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get status by Id params
func (o *GetStatusByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get status by Id params
func (o *GetStatusByIDParams) WithContext(ctx context.Context) *GetStatusByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get status by Id params
func (o *GetStatusByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get status by Id params
func (o *GetStatusByIDParams) WithHTTPClient(client *http.Client) *GetStatusByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get status by Id params
func (o *GetStatusByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get status by Id params
func (o *GetStatusByIDParams) WithID(id int64) *GetStatusByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get status by Id params
func (o *GetStatusByIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetStatusByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
