// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetStatusesParams creates a new GetStatusesParams object
// with the default values initialized.
func NewGetStatusesParams() *GetStatusesParams {
	var ()
	return &GetStatusesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetStatusesParamsWithTimeout creates a new GetStatusesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetStatusesParamsWithTimeout(timeout time.Duration) *GetStatusesParams {
	var ()
	return &GetStatusesParams{

		timeout: timeout,
	}
}

// NewGetStatusesParamsWithContext creates a new GetStatusesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetStatusesParamsWithContext(ctx context.Context) *GetStatusesParams {
	var ()
	return &GetStatusesParams{

		Context: ctx,
	}
}

// NewGetStatusesParamsWithHTTPClient creates a new GetStatusesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetStatusesParamsWithHTTPClient(client *http.Client) *GetStatusesParams {
	var ()
	return &GetStatusesParams{
		HTTPClient: client,
	}
}

/*GetStatusesParams contains all the parameters to send to the API endpoint
for the get statuses operation typically these are written to a http.Request
*/
type GetStatusesParams struct {

	/*Description
	  A short description of the status

	*/
	Description *string
	/*ID
	  Unique identifier for the Status

	*/
	ID *string
	/*Name
	  The name that refers to this Status

	*/
	Name *string
	/*Orderby*/
	Orderby *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get statuses params
func (o *GetStatusesParams) WithTimeout(timeout time.Duration) *GetStatusesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get statuses params
func (o *GetStatusesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get statuses params
func (o *GetStatusesParams) WithContext(ctx context.Context) *GetStatusesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get statuses params
func (o *GetStatusesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get statuses params
func (o *GetStatusesParams) WithHTTPClient(client *http.Client) *GetStatusesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get statuses params
func (o *GetStatusesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDescription adds the description to the get statuses params
func (o *GetStatusesParams) WithDescription(description *string) *GetStatusesParams {
	o.SetDescription(description)
	return o
}

// SetDescription adds the description to the get statuses params
func (o *GetStatusesParams) SetDescription(description *string) {
	o.Description = description
}

// WithID adds the id to the get statuses params
func (o *GetStatusesParams) WithID(id *string) *GetStatusesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get statuses params
func (o *GetStatusesParams) SetID(id *string) {
	o.ID = id
}

// WithName adds the name to the get statuses params
func (o *GetStatusesParams) WithName(name *string) *GetStatusesParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get statuses params
func (o *GetStatusesParams) SetName(name *string) {
	o.Name = name
}

// WithOrderby adds the orderby to the get statuses params
func (o *GetStatusesParams) WithOrderby(orderby *string) *GetStatusesParams {
	o.SetOrderby(orderby)
	return o
}

// SetOrderby adds the orderby to the get statuses params
func (o *GetStatusesParams) SetOrderby(orderby *string) {
	o.Orderby = orderby
}

// WriteToRequest writes these params to a swagger request
func (o *GetStatusesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Description != nil {

		// query param description
		var qrDescription string
		if o.Description != nil {
			qrDescription = *o.Description
		}
		qDescription := qrDescription
		if qDescription != "" {
			if err := r.SetQueryParam("description", qDescription); err != nil {
				return err
			}
		}

	}

	if o.ID != nil {

		// query param id
		var qrID string
		if o.ID != nil {
			qrID = *o.ID
		}
		qID := qrID
		if qID != "" {
			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}

	}

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if o.Orderby != nil {

		// query param orderby
		var qrOrderby string
		if o.Orderby != nil {
			qrOrderby = *o.Orderby
		}
		qOrderby := qrOrderby
		if qOrderby != "" {
			if err := r.SetQueryParam("orderby", qOrderby); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
