// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/apache/incubator-trafficcontrol/traffic_ops/traffic_ops_golang/toclient/models"
)

// GetStatusByIDReader is a Reader for the GetStatusByID structure.
type GetStatusByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetStatusByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetStatusByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetStatusByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetStatusByIDOK creates a GetStatusByIDOK with default headers values
func NewGetStatusByIDOK() *GetStatusByIDOK {
	return &GetStatusByIDOK{}
}

/*GetStatusByIDOK handles this case with default header values.

Statuses -  StatusesResponse to get the "response" top level key
*/
type GetStatusByIDOK struct {
	Payload *models.StatusesResponse
}

func (o *GetStatusByIDOK) Error() string {
	return fmt.Sprintf("[GET /statuses/{id}][%d] getStatusByIdOK  %+v", 200, o.Payload)
}

func (o *GetStatusByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StatusesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetStatusByIDBadRequest creates a GetStatusByIDBadRequest with default headers values
func NewGetStatusByIDBadRequest() *GetStatusByIDBadRequest {
	return &GetStatusByIDBadRequest{}
}

/*GetStatusByIDBadRequest handles this case with default header values.

Alerts - informs the client of server side messages
*/
type GetStatusByIDBadRequest struct {
	Payload models.GetStatusByIDBadRequestBody
}

func (o *GetStatusByIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /statuses/{id}][%d] getStatusByIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetStatusByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
