// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/apache/incubator-trafficcontrol/traffic_ops/traffic_ops_golang/toclient/models"
)

// NewPutStatusParams creates a new PutStatusParams object
// with the default values initialized.
func NewPutStatusParams() *PutStatusParams {
	var ()
	return &PutStatusParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutStatusParamsWithTimeout creates a new PutStatusParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutStatusParamsWithTimeout(timeout time.Duration) *PutStatusParams {
	var ()
	return &PutStatusParams{

		timeout: timeout,
	}
}

// NewPutStatusParamsWithContext creates a new PutStatusParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutStatusParamsWithContext(ctx context.Context) *PutStatusParams {
	var ()
	return &PutStatusParams{

		Context: ctx,
	}
}

// NewPutStatusParamsWithHTTPClient creates a new PutStatusParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutStatusParamsWithHTTPClient(client *http.Client) *PutStatusParams {
	var ()
	return &PutStatusParams{
		HTTPClient: client,
	}
}

/*PutStatusParams contains all the parameters to send to the API endpoint
for the put status operation typically these are written to a http.Request
*/
type PutStatusParams struct {

	/*Status
	  Status Request Body

	*/
	Status *models.Status
	/*ID
	  ID

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put status params
func (o *PutStatusParams) WithTimeout(timeout time.Duration) *PutStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put status params
func (o *PutStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put status params
func (o *PutStatusParams) WithContext(ctx context.Context) *PutStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put status params
func (o *PutStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put status params
func (o *PutStatusParams) WithHTTPClient(client *http.Client) *PutStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put status params
func (o *PutStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithStatus adds the status to the put status params
func (o *PutStatusParams) WithStatus(status *models.Status) *PutStatusParams {
	o.SetStatus(status)
	return o
}

// SetStatus adds the status to the put status params
func (o *PutStatusParams) SetStatus(status *models.Status) {
	o.Status = status
}

// WithID adds the id to the put status params
func (o *PutStatusParams) WithID(id int64) *PutStatusParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put status params
func (o *PutStatusParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Status != nil {
		if err := r.SetBodyParam(o.Status); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
