// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/apache/incubator-trafficcontrol/traffic_ops/traffic_ops_golang/toclient/models"
)

// PutStatusReader is a Reader for the PutStatus structure.
type PutStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutStatusOK creates a PutStatusOK with default headers values
func NewPutStatusOK() *PutStatusOK {
	return &PutStatusOK{}
}

/*PutStatusOK handles this case with default header values.

Status -  StatusResponse to get the "response" top level key
*/
type PutStatusOK struct {
	Payload *models.StatusResponse
}

func (o *PutStatusOK) Error() string {
	return fmt.Sprintf("[PUT /statuses/{id}][%d] putStatusOK  %+v", 200, o.Payload)
}

func (o *PutStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
