// Code generated by go-swagger; DO NOT EDIT.

package division

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/apache/incubator-trafficcontrol/traffic_ops/traffic_ops_golang/toclient/models"
)

// DeleteDivisionReader is a Reader for the DeleteDivision structure.
type DeleteDivisionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDivisionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteDivisionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteDivisionOK creates a DeleteDivisionOK with default headers values
func NewDeleteDivisionOK() *DeleteDivisionOK {
	return &DeleteDivisionOK{}
}

/*DeleteDivisionOK handles this case with default header values.

Alerts - informs the client of server side messages
*/
type DeleteDivisionOK struct {
	Payload models.DeleteDivisionOKBody
}

func (o *DeleteDivisionOK) Error() string {
	return fmt.Sprintf("[DELETE /divisions/{id}][%d] deleteDivisionOK  %+v", 200, o.Payload)
}

func (o *DeleteDivisionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
