// Code generated by go-swagger; DO NOT EDIT.

package division

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDivisionsParams creates a new GetDivisionsParams object
// with the default values initialized.
func NewGetDivisionsParams() *GetDivisionsParams {
	var ()
	return &GetDivisionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDivisionsParamsWithTimeout creates a new GetDivisionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDivisionsParamsWithTimeout(timeout time.Duration) *GetDivisionsParams {
	var ()
	return &GetDivisionsParams{

		timeout: timeout,
	}
}

// NewGetDivisionsParamsWithContext creates a new GetDivisionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDivisionsParamsWithContext(ctx context.Context) *GetDivisionsParams {
	var ()
	return &GetDivisionsParams{

		Context: ctx,
	}
}

// NewGetDivisionsParamsWithHTTPClient creates a new GetDivisionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDivisionsParamsWithHTTPClient(client *http.Client) *GetDivisionsParams {
	var ()
	return &GetDivisionsParams{
		HTTPClient: client,
	}
}

/*GetDivisionsParams contains all the parameters to send to the API endpoint
for the get divisions operation typically these are written to a http.Request
*/
type GetDivisionsParams struct {

	/*ID
	  Unique identifier for the Division

	*/
	ID *string
	/*Name
	  Name for this Division

	*/
	Name *string
	/*Orderby*/
	Orderby *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get divisions params
func (o *GetDivisionsParams) WithTimeout(timeout time.Duration) *GetDivisionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get divisions params
func (o *GetDivisionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get divisions params
func (o *GetDivisionsParams) WithContext(ctx context.Context) *GetDivisionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get divisions params
func (o *GetDivisionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get divisions params
func (o *GetDivisionsParams) WithHTTPClient(client *http.Client) *GetDivisionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get divisions params
func (o *GetDivisionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get divisions params
func (o *GetDivisionsParams) WithID(id *string) *GetDivisionsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get divisions params
func (o *GetDivisionsParams) SetID(id *string) {
	o.ID = id
}

// WithName adds the name to the get divisions params
func (o *GetDivisionsParams) WithName(name *string) *GetDivisionsParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get divisions params
func (o *GetDivisionsParams) SetName(name *string) {
	o.Name = name
}

// WithOrderby adds the orderby to the get divisions params
func (o *GetDivisionsParams) WithOrderby(orderby *string) *GetDivisionsParams {
	o.SetOrderby(orderby)
	return o
}

// SetOrderby adds the orderby to the get divisions params
func (o *GetDivisionsParams) SetOrderby(orderby *string) {
	o.Orderby = orderby
}

// WriteToRequest writes these params to a swagger request
func (o *GetDivisionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ID != nil {

		// query param id
		var qrID string
		if o.ID != nil {
			qrID = *o.ID
		}
		qID := qrID
		if qID != "" {
			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}

	}

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if o.Orderby != nil {

		// query param orderby
		var qrOrderby string
		if o.Orderby != nil {
			qrOrderby = *o.Orderby
		}
		qOrderby := qrOrderby
		if qOrderby != "" {
			if err := r.SetQueryParam("orderby", qOrderby); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
