// Code generated by go-swagger; DO NOT EDIT.

package division

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDivisionByIDParams creates a new GetDivisionByIDParams object
// with the default values initialized.
func NewGetDivisionByIDParams() *GetDivisionByIDParams {
	var ()
	return &GetDivisionByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDivisionByIDParamsWithTimeout creates a new GetDivisionByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDivisionByIDParamsWithTimeout(timeout time.Duration) *GetDivisionByIDParams {
	var ()
	return &GetDivisionByIDParams{

		timeout: timeout,
	}
}

// NewGetDivisionByIDParamsWithContext creates a new GetDivisionByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDivisionByIDParamsWithContext(ctx context.Context) *GetDivisionByIDParams {
	var ()
	return &GetDivisionByIDParams{

		Context: ctx,
	}
}

// NewGetDivisionByIDParamsWithHTTPClient creates a new GetDivisionByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDivisionByIDParamsWithHTTPClient(client *http.Client) *GetDivisionByIDParams {
	var ()
	return &GetDivisionByIDParams{
		HTTPClient: client,
	}
}

/*GetDivisionByIDParams contains all the parameters to send to the API endpoint
for the get division by Id operation typically these are written to a http.Request
*/
type GetDivisionByIDParams struct {

	/*ID
	  Id associated to the Division

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get division by Id params
func (o *GetDivisionByIDParams) WithTimeout(timeout time.Duration) *GetDivisionByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get division by Id params
func (o *GetDivisionByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get division by Id params
func (o *GetDivisionByIDParams) WithContext(ctx context.Context) *GetDivisionByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get division by Id params
func (o *GetDivisionByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get division by Id params
func (o *GetDivisionByIDParams) WithHTTPClient(client *http.Client) *GetDivisionByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get division by Id params
func (o *GetDivisionByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get division by Id params
func (o *GetDivisionByIDParams) WithID(id int64) *GetDivisionByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get division by Id params
func (o *GetDivisionByIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetDivisionByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
