// Code generated by go-swagger; DO NOT EDIT.

package division

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/apache/incubator-trafficcontrol/traffic_ops/traffic_ops_golang/toclient/models"
)

// PutDivisionReader is a Reader for the PutDivision structure.
type PutDivisionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutDivisionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutDivisionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutDivisionOK creates a PutDivisionOK with default headers values
func NewPutDivisionOK() *PutDivisionOK {
	return &PutDivisionOK{}
}

/*PutDivisionOK handles this case with default header values.

Division -  DivisionResponse to get the "response" top level key
*/
type PutDivisionOK struct {
	Payload *models.DivisionResponse
}

func (o *PutDivisionOK) Error() string {
	return fmt.Sprintf("[PUT /divisions/{id}][%d] putDivisionOK  %+v", 200, o.Payload)
}

func (o *PutDivisionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DivisionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
