// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteCDNHandlerFunc turns a function with the right signature into a delete c d n handler
type DeleteCDNHandlerFunc func(DeleteCDNParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteCDNHandlerFunc) Handle(params DeleteCDNParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteCDNHandler interface for that can handle valid delete c d n params
type DeleteCDNHandler interface {
	Handle(DeleteCDNParams, interface{}) middleware.Responder
}

// NewDeleteCDN creates a new http.Handler for the delete c d n operation
func NewDeleteCDN(ctx *middleware.Context, handler DeleteCDNHandler) *DeleteCDN {
	return &DeleteCDN{Context: ctx, Handler: handler}
}

/*DeleteCDN swagger:route DELETE /cdns/{id} CDN deleteCDN

Delete a CDN

*/
type DeleteCDN struct {
	Context *middleware.Context
	Handler DeleteCDNHandler
}

func (o *DeleteCDN) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteCDNParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
