// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/apache/incubator-trafficcontrol.tor-api/traffic_ops/traffic_ops_golang/toclient/models"
)

// DeleteCDNOKCode is the HTTP code returned for type DeleteCDNOK
const DeleteCDNOKCode int = 200

/*DeleteCDNOK Alerts - informs the client of server side messages

swagger:response deleteCDNOK
*/
type DeleteCDNOK struct {

	/*
	  In: Body
	*/
	Payload models.DeleteCDNOKBody `json:"body,omitempty"`
}

// NewDeleteCDNOK creates DeleteCDNOK with default headers values
func NewDeleteCDNOK() *DeleteCDNOK {
	return &DeleteCDNOK{}
}

// WithPayload adds the payload to the delete c d n o k response
func (o *DeleteCDNOK) WithPayload(payload models.DeleteCDNOKBody) *DeleteCDNOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete c d n o k response
func (o *DeleteCDNOK) SetPayload(payload models.DeleteCDNOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteCDNOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.DeleteCDNOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
