// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetCDNByIDHandlerFunc turns a function with the right signature into a get c d n by Id handler
type GetCDNByIDHandlerFunc func(GetCDNByIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCDNByIDHandlerFunc) Handle(params GetCDNByIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetCDNByIDHandler interface for that can handle valid get c d n by Id params
type GetCDNByIDHandler interface {
	Handle(GetCDNByIDParams, interface{}) middleware.Responder
}

// NewGetCDNByID creates a new http.Handler for the get c d n by Id operation
func NewGetCDNByID(ctx *middleware.Context, handler GetCDNByIDHandler) *GetCDNByID {
	return &GetCDNByID{Context: ctx, Handler: handler}
}

/*GetCDNByID swagger:route GET /cdns/{id} CDN getCDNById

Retrieve a specific CDN

*/
type GetCDNByID struct {
	Context *middleware.Context
	Handler GetCDNByIDHandler
}

func (o *GetCDNByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCDNByIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
