// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostCDNHandlerFunc turns a function with the right signature into a post c d n handler
type PostCDNHandlerFunc func(PostCDNParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostCDNHandlerFunc) Handle(params PostCDNParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostCDNHandler interface for that can handle valid post c d n params
type PostCDNHandler interface {
	Handle(PostCDNParams, interface{}) middleware.Responder
}

// NewPostCDN creates a new http.Handler for the post c d n operation
func NewPostCDN(ctx *middleware.Context, handler PostCDNHandler) *PostCDN {
	return &PostCDN{Context: ctx, Handler: handler}
}

/*PostCDN swagger:route POST /cdns CDN postCDN

Create a CDN

*/
type PostCDN struct {
	Context *middleware.Context
	Handler PostCDNHandler
}

func (o *PostCDN) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostCDNParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
