// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/apache/incubator-trafficcontrol.tor-api/traffic_ops/traffic_ops_golang/toclient/models"
)

// NewPostCDNParams creates a new PostCDNParams object
// with the default values initialized.
func NewPostCDNParams() PostCDNParams {
	var ()
	return PostCDNParams{}
}

// PostCDNParams contains all the bound params for the post c d n operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostCDN
type PostCDNParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*CDN Request Body
	  Required: true
	  In: body
	*/
	CDN *models.CDN
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *PostCDNParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.CDN
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("cDN", "body"))
			} else {
				res = append(res, errors.NewParseError("cDN", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.CDN = &body
			}
		}

	} else {
		res = append(res, errors.Required("cDN", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
