// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/apache/incubator-trafficcontrol.tor-api/traffic_ops/traffic_ops_golang/toclient/models"
)

// PutCDNOKCode is the HTTP code returned for type PutCDNOK
const PutCDNOKCode int = 200

/*PutCDNOK CDN -  CDNResponse to get the "response" top level key

swagger:response putCDNOK
*/
type PutCDNOK struct {

	/*
	  In: Body
	*/
	Payload *models.CDNResponse `json:"body,omitempty"`
}

// NewPutCDNOK creates PutCDNOK with default headers values
func NewPutCDNOK() *PutCDNOK {
	return &PutCDNOK{}
}

// WithPayload adds the payload to the put c d n o k response
func (o *PutCDNOK) WithPayload(payload *models.CDNResponse) *PutCDNOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put c d n o k response
func (o *PutCDNOK) SetPayload(payload *models.CDNResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutCDNOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
