// Code generated by go-swagger; DO NOT EDIT.

package cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PutCDNHandlerFunc turns a function with the right signature into a put c d n handler
type PutCDNHandlerFunc func(PutCDNParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PutCDNHandlerFunc) Handle(params PutCDNParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PutCDNHandler interface for that can handle valid put c d n params
type PutCDNHandler interface {
	Handle(PutCDNParams, interface{}) middleware.Responder
}

// NewPutCDN creates a new http.Handler for the put c d n operation
func NewPutCDN(ctx *middleware.Context, handler PutCDNHandler) *PutCDN {
	return &PutCDN{Context: ctx, Handler: handler}
}

/*PutCDN swagger:route PUT /cdns/{id} CDN putCDN

Update a CDN

*/
type PutCDN struct {
	Context *middleware.Context
	Handler PutCDNHandler
}

func (o *PutCDN) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutCDNParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
