// Code generated by go-swagger; DO NOT EDIT.

package asn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/apache/incubator-trafficcontrol.tor-api/traffic_ops/traffic_ops_golang/toclient/models"
)

// DeleteASNOKCode is the HTTP code returned for type DeleteASNOK
const DeleteASNOKCode int = 200

/*DeleteASNOK Alerts - informs the client of server side messages

swagger:response deleteASNOK
*/
type DeleteASNOK struct {

	/*
	  In: Body
	*/
	Payload models.DeleteASNOKBody `json:"body,omitempty"`
}

// NewDeleteASNOK creates DeleteASNOK with default headers values
func NewDeleteASNOK() *DeleteASNOK {
	return &DeleteASNOK{}
}

// WithPayload adds the payload to the delete a s n o k response
func (o *DeleteASNOK) WithPayload(payload models.DeleteASNOKBody) *DeleteASNOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete a s n o k response
func (o *DeleteASNOK) SetPayload(payload models.DeleteASNOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteASNOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.DeleteASNOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
