// Code generated by go-swagger; DO NOT EDIT.

package asn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteASNHandlerFunc turns a function with the right signature into a delete a s n handler
type DeleteASNHandlerFunc func(DeleteASNParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteASNHandlerFunc) Handle(params DeleteASNParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteASNHandler interface for that can handle valid delete a s n params
type DeleteASNHandler interface {
	Handle(DeleteASNParams, interface{}) middleware.Responder
}

// NewDeleteASN creates a new http.Handler for the delete a s n operation
func NewDeleteASN(ctx *middleware.Context, handler DeleteASNHandler) *DeleteASN {
	return &DeleteASN{Context: ctx, Handler: handler}
}

/*DeleteASN swagger:route DELETE /asns/{id} ASN deleteASN

Delete a ASN

*/
type DeleteASN struct {
	Context *middleware.Context
	Handler DeleteASNHandler
}

func (o *DeleteASN) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteASNParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
