// Code generated by go-swagger; DO NOT EDIT.

package asn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetASNsHandlerFunc turns a function with the right signature into a get a s ns handler
type GetASNsHandlerFunc func(GetASNsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetASNsHandlerFunc) Handle(params GetASNsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetASNsHandler interface for that can handle valid get a s ns params
type GetASNsHandler interface {
	Handle(GetASNsParams, interface{}) middleware.Responder
}

// NewGetASNs creates a new http.Handler for the get a s ns operation
func NewGetASNs(ctx *middleware.Context, handler GetASNsHandler) *GetASNs {
	return &GetASNs{Context: ctx, Handler: handler}
}

/*GetASNs swagger:route GET /asns ASN getASNs

Retrieve a list of ASNs

*/
type GetASNs struct {
	Context *middleware.Context
	Handler GetASNsHandler
}

func (o *GetASNs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetASNsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
