// Code generated by go-swagger; DO NOT EDIT.

package asn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostASNHandlerFunc turns a function with the right signature into a post a s n handler
type PostASNHandlerFunc func(PostASNParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostASNHandlerFunc) Handle(params PostASNParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostASNHandler interface for that can handle valid post a s n params
type PostASNHandler interface {
	Handle(PostASNParams, interface{}) middleware.Responder
}

// NewPostASN creates a new http.Handler for the post a s n operation
func NewPostASN(ctx *middleware.Context, handler PostASNHandler) *PostASN {
	return &PostASN{Context: ctx, Handler: handler}
}

/*PostASN swagger:route POST /asns ASN postASN

Create a ASN

*/
type PostASN struct {
	Context *middleware.Context
	Handler PostASNHandler
}

func (o *PostASN) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostASNParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
