// Code generated by go-swagger; DO NOT EDIT.

package region

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteRegionHandlerFunc turns a function with the right signature into a delete region handler
type DeleteRegionHandlerFunc func(DeleteRegionParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteRegionHandlerFunc) Handle(params DeleteRegionParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteRegionHandler interface for that can handle valid delete region params
type DeleteRegionHandler interface {
	Handle(DeleteRegionParams, interface{}) middleware.Responder
}

// NewDeleteRegion creates a new http.Handler for the delete region operation
func NewDeleteRegion(ctx *middleware.Context, handler DeleteRegionHandler) *DeleteRegion {
	return &DeleteRegion{Context: ctx, Handler: handler}
}

/*DeleteRegion swagger:route DELETE /regions/{id} Region deleteRegion

Delete a Region

*/
type DeleteRegion struct {
	Context *middleware.Context
	Handler DeleteRegionHandler
}

func (o *DeleteRegion) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteRegionParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
