// Code generated by go-swagger; DO NOT EDIT.

package region

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/apache/incubator-trafficcontrol.tor-api/traffic_ops/traffic_ops_golang/toserver/models"
)

// DeleteRegionOKCode is the HTTP code returned for type DeleteRegionOK
const DeleteRegionOKCode int = 200

/*DeleteRegionOK Alerts - informs the client of server side messages

swagger:response deleteRegionOK
*/
type DeleteRegionOK struct {

	/*
	  In: Body
	*/
	Payload models.DeleteRegionOKBody `json:"body,omitempty"`
}

// NewDeleteRegionOK creates DeleteRegionOK with default headers values
func NewDeleteRegionOK() *DeleteRegionOK {
	return &DeleteRegionOK{}
}

// WithPayload adds the payload to the delete region o k response
func (o *DeleteRegionOK) WithPayload(payload models.DeleteRegionOKBody) *DeleteRegionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete region o k response
func (o *DeleteRegionOK) SetPayload(payload models.DeleteRegionOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteRegionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.DeleteRegionOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
