// Code generated by go-swagger; DO NOT EDIT.

package region

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetRegionByIDHandlerFunc turns a function with the right signature into a get region by Id handler
type GetRegionByIDHandlerFunc func(GetRegionByIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRegionByIDHandlerFunc) Handle(params GetRegionByIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetRegionByIDHandler interface for that can handle valid get region by Id params
type GetRegionByIDHandler interface {
	Handle(GetRegionByIDParams, interface{}) middleware.Responder
}

// NewGetRegionByID creates a new http.Handler for the get region by Id operation
func NewGetRegionByID(ctx *middleware.Context, handler GetRegionByIDHandler) *GetRegionByID {
	return &GetRegionByID{Context: ctx, Handler: handler}
}

/*GetRegionByID swagger:route GET /regions/{id} Region getRegionById

Retrieve a specific Region

*/
type GetRegionByID struct {
	Context *middleware.Context
	Handler GetRegionByIDHandler
}

func (o *GetRegionByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetRegionByIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
