// Code generated by go-swagger; DO NOT EDIT.

package region

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostRegionHandlerFunc turns a function with the right signature into a post region handler
type PostRegionHandlerFunc func(PostRegionParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostRegionHandlerFunc) Handle(params PostRegionParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostRegionHandler interface for that can handle valid post region params
type PostRegionHandler interface {
	Handle(PostRegionParams, interface{}) middleware.Responder
}

// NewPostRegion creates a new http.Handler for the post region operation
func NewPostRegion(ctx *middleware.Context, handler PostRegionHandler) *PostRegion {
	return &PostRegion{Context: ctx, Handler: handler}
}

/*PostRegion swagger:route POST /regions Region postRegion

Create a Region

*/
type PostRegion struct {
	Context *middleware.Context
	Handler PostRegionHandler
}

func (o *PostRegion) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostRegionParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
