// Code generated by go-swagger; DO NOT EDIT.

package region

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/apache/incubator-trafficcontrol.tor-api/traffic_ops/traffic_ops_golang/toserver/models"
)

// NewPostRegionParams creates a new PostRegionParams object
// with the default values initialized.
func NewPostRegionParams() PostRegionParams {
	var ()
	return PostRegionParams{}
}

// PostRegionParams contains all the bound params for the post region operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostRegion
type PostRegionParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Region Request Body
	  Required: true
	  In: body
	*/
	Region *models.Region
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *PostRegionParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Region
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("region", "body"))
			} else {
				res = append(res, errors.NewParseError("region", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Region = &body
			}
		}

	} else {
		res = append(res, errors.Required("region", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
