// Code generated by go-swagger; DO NOT EDIT.

package region

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PutRegionHandlerFunc turns a function with the right signature into a put region handler
type PutRegionHandlerFunc func(PutRegionParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PutRegionHandlerFunc) Handle(params PutRegionParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PutRegionHandler interface for that can handle valid put region params
type PutRegionHandler interface {
	Handle(PutRegionParams, interface{}) middleware.Responder
}

// NewPutRegion creates a new http.Handler for the put region operation
func NewPutRegion(ctx *middleware.Context, handler PutRegionHandler) *PutRegion {
	return &PutRegion{Context: ctx, Handler: handler}
}

/*PutRegion swagger:route PUT /regions/{id} Region putRegion

Update a Region

*/
type PutRegion struct {
	Context *middleware.Context
	Handler PutRegionHandler
}

func (o *PutRegion) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutRegionParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
